apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
  - image: solidnerd/prometheus-service
    docker:
      dockerfile: Dockerfile
      buildArgs:
        debugBuild: "true"
deploy:
  kubectl:
    manifests:
    - deploy/service.yaml
